k8s_masters:
  hosts:
    # Control nodes
    master_node1:
      ansible_host: 192.168.0.100
k8s_workers:
  hosts:
    # Worker nodes
    worker_node1:
      ansible_host: 192.168.0.101
k8s_cluster:
  children:
    k8s_masters:
    k8s_workers:
