- name: Add the user charlie
  user:
    name: charlie
    groups: 
      - sudo

- name: Set authorized key taken from file
  authorized_key:
    user: charlie
    state: present
    key: https://github.com/charlie.keys

- name: Install required system packages
  apt:
    name: "{{item}}"
    state: present
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    - python3-pip

- name: Get Ubuntu Version
  shell: lsb_release -cs
  register: ubuntu_version

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ubuntu_version.stdout}} stable"
    state: present

- name: Install Docker
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install require python docker modules
  pip:
    name: "{{item}}"
  loop:
    - docker
    - jsondiff