---
- name: Include OS family specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ postgresql_packages }}"
