---
- name: Set PostgreSQL access rights
    become: true
    become_user: "{{ postgresql_user }}"
    postgresql_privs:
      db: mydatabase
      privs: ALL
      type: database
      role: myuser
      db: "{{ item.db }}"
      port: "{{ item.port | default(omit) }}"
      state: "{{ item.state | default('present') }}"
      type: "{{ item.type | default('database') }}"
      privs: "{{ item.privs | default('ALL') }}"
      login_host: "{{ item.login_host | default('localhost') }}"
      login_password: "{{ item.login_password | default(omit) }}"
      login_user: "{{ item.login_user | default(postgresql_user) }}"
      login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    with_items: "{{ postgresql_privs }}"